//General
export const LOADING = "LOADING"
export const ERROR = "ERROR"
export const LOAD_MORE = "LOAD_MORE"

// Price
export const GET_LIST_PRICE_SHRIMP = "GET_LIST_PRICE_SHRIMP"
export const LOAD_MORE_PRICE_SHRIMP = "LOAD_MORE_PRICE_SHRIMP"
export const SEARCH_PRICE_SHRIMP = "SEARCH_PRICE_SHRIMP"

// News
export const GET_LIST_NEWS_SHRIMP = "GET_LIST_NEWS_SHRIMP"
export const LOAD_MORE_NEWS_SHRIMP = "LOAD_MORE_NEWS_SHRIMP"

// Diseases
export const GET_LIST_DISEASES_SHRIMP = "GET_LIST_DISEASES_SHRIMP"
export const LOAD_MORE_DISEASES_SHRIMP = "LOAD_MORE_DISEASES_SHRIMP"

// Region
export const GET_LIST_REGION = "GET_LIST_REGION"
export const LOAD_MORE_REGION = "SEARCH_REGION"